Add ctime to thermostat.h
This fixes the compile error:

❯ .piolibdeps/mitsubishi-heat-pump/itp-packet/src/packets/thermostat.cpp: In member function 'virtual std::string itp_packet::ThermostatStateUploadPacket::to_string() const':
  .piolibdeps/mitsubishi-heat-pump/itp-packet/src/packets/thermostat.cpp:24:15: error: variable 'tm ts_timestamp' has initializer but incomplete type
     24 |     struct tm ts_timestamp = get_thermostat_timestamp();
        |               ^~~~~~~~~~~~
  .piolibdeps/mitsubishi-heat-pump/itp-packet/src/packets/thermostat.cpp:24:55: error: invalid use of incomplete type 'struct tm'
     24 |     struct tm ts_timestamp = get_thermostat_timestamp();

The error is because <ctime> isn't included — struct tm and strftime need it.